Add ERC7412 utility functions
Parifi/synthetix-sdk-ts pull request #4
Opened 2024-09-03 18:03 UTC by sudeepb02

2024-09-09 08:44 UTC, Akhilleshgoswami approved these changes

2024-09-09 16:56 UTC, racso2609 requested changes

2024-09-09 16:56 UTC, racso2609 commented on src/utils/common.ts
> +export function getViemChain(chainId: number): Chain {
i think we should try to avoid this type of names. It better just say ```getChain``` in the future the implementation of this function could chain, maybe you could change the library used or anything and the name doesnt make any more sense. Also change the name on the function on all places and even in application that integrate the function is a breaking changes. Always is better have generic names abstracted to the implementation

2024-09-10 11:29 UTC, sudeepb02 commented on src/utils/common.ts
> +export function getViemChain(chainId: number): Chain {
Updated

2024-09-10 11:34 UTC, merged